<?php

namespace StoreBundle\Repository;

/**
 * ProductHasCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductHasCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
